name: Deploy to Firebase Hosting on new MotionLink tag
"on":
  push:
    tags:
      - "motion-link-*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOTIONLINK_AEC23 }}"
          projectId: motionlink-aec23
          channelId: live
